services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: thai_meet
      POSTGRES_PASSWORD: thai_meet
      POSTGRES_DB: thai_meet
    ports:
      - "5432:5432"
    volumes:
      - thai_meet_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  thai_meet_postgres:
